"""create initial port monitoring schema

Revision ID: 937231985be4
Revises:
Create Date: 2026-08-26 21:38:51.618258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '937231985be4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='audit_action'), nullable=False),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_records_created_at', 'audit_records', ['created_at'], unique=False)
    op.create_index('ix_audit_records_entity', 'audit_records', ['entity_name', 'entity_id'], unique=False)
    op.create_table('berths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'MAINTENANCE', name='berth_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vessels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('imo_reference', sa.String(length=20), nullable=True),
    sa.Column('capacity_t', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('agent_name', sa.String(length=150), nullable=True),
    sa.Column('agent_phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity_t IS NULL OR capacity_t > 0', name='ck_vessels_capacity_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imo_reference')
    )
    op.create_table('upcoming_vessel_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vessel_id', sa.UUID(), nullable=False),
    sa.Column('berth_id', sa.UUID(), nullable=False),
    sa.Column('expected_arrival', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cargo_type', sa.String(length=100), nullable=False),
    sa.Column('cargo_quantity_t', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_rate_tph', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('call_alert_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmation_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('berth_preparation_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'CONFIRMED', 'ARRIVED', 'CANCELLED', name='upcoming_call_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('berth_preparation_minutes >= 0', name='ck_upcoming_calls_preparation_nonnegative'),
    sa.CheckConstraint('call_alert_at IS NULL OR call_alert_at <= expected_arrival', name='ck_upcoming_calls_alert_before_arrival'),
    sa.CheckConstraint('cargo_quantity_t > 0', name='ck_upcoming_calls_cargo_positive'),
    sa.CheckConstraint('confirmation_due_at IS NULL OR confirmation_due_at <= expected_arrival', name='ck_upcoming_calls_confirmation_before_arrival'),
    sa.CheckConstraint('expected_rate_tph IS NULL OR expected_rate_tph > 0', name='ck_upcoming_calls_rate_positive'),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_upcoming_calls_expected_arrival', 'upcoming_vessel_calls', ['expected_arrival'], unique=False)
    op.create_index('ix_upcoming_calls_status', 'upcoming_vessel_calls', ['status'], unique=False)
    op.create_table('vessel_visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vessel_id', sa.UUID(), nullable=False),
    sa.Column('berth_id', sa.UUID(), nullable=False),
    sa.Column('cargo_type', sa.String(length=100), nullable=False),
    sa.Column('cargo_total_t', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('planned_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unload_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unload_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('post_unloading_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'ARRIVED', 'UNLOADING', 'COMPLETED', 'DEPARTED', 'CANCELLED', name='visit_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_departure IS NULL OR actual_arrival IS NULL OR actual_departure >= actual_arrival', name='ck_vessel_visits_departure_times'),
    sa.CheckConstraint('cargo_total_t > 0', name='ck_vessel_visits_cargo_positive'),
    sa.CheckConstraint('post_unloading_minutes >= 0', name='ck_vessel_visits_post_unloading_nonnegative'),
    sa.CheckConstraint('unload_end IS NULL OR unload_start IS NULL OR unload_end >= unload_start', name='ck_vessel_visits_unload_times'),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vessel_visits_berth_id', 'vessel_visits', ['berth_id'], unique=False)
    op.create_index('ix_vessel_visits_planned_arrival', 'vessel_visits', ['planned_arrival'], unique=False)
    op.create_index('ix_vessel_visits_status', 'vessel_visits', ['status'], unique=False)
    op.create_index('ix_vessel_visits_vessel_id', 'vessel_visits', ['vessel_id'], unique=False)
    op.create_table('delay_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('cause', sa.String(length=150), nullable=False),
    sa.Column('responsible_area', sa.String(length=100), nullable=True),
    sa.Column('equipment', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_time IS NULL OR end_time >= start_time', name='ck_delay_events_valid_times'),
    sa.ForeignKeyConstraint(['visit_id'], ['vessel_visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_delay_events_category', 'delay_events', ['category'], unique=False)
    op.create_index('ix_delay_events_visit_id', 'delay_events', ['visit_id'], unique=False)
    op.create_table('operational_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'CSV', 'DEMO', name='reading_source'), nullable=False),
    sa.Column('unloaded_t', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observed_rate_tph', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('buffer_level_t', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('buffer_capacity_t', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('packaging_rate_tph', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unloading_status', sa.Enum('ACTIVE', 'STOPPED', 'COMPLETED', name='unloading_status'), nullable=False),
    sa.Column('packaging_status', sa.Enum('ACTIVE', 'STOPPED', 'NOT_APPLICABLE', name='packaging_status'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('buffer_capacity_t IS NULL OR buffer_capacity_t > 0', name='ck_operational_readings_capacity_positive'),
    sa.CheckConstraint('buffer_level_t IS NULL OR buffer_capacity_t IS NULL OR buffer_level_t <= buffer_capacity_t', name='ck_operational_readings_buffer_within_capacity'),
    sa.CheckConstraint('buffer_level_t IS NULL OR buffer_level_t >= 0', name='ck_operational_readings_buffer_nonnegative'),
    sa.CheckConstraint('observed_rate_tph IS NULL OR observed_rate_tph >= 0', name='ck_operational_readings_rate_nonnegative'),
    sa.CheckConstraint('packaging_rate_tph IS NULL OR packaging_rate_tph >= 0', name='ck_operational_readings_packaging_rate_nonnegative'),
    sa.CheckConstraint('unloaded_t >= 0', name='ck_operational_readings_unloaded_nonnegative'),
    sa.ForeignKeyConstraint(['visit_id'], ['vessel_visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id', 'recorded_at', name='uq_operational_readings_visit_recorded_at')
    )
    op.create_index('ix_operational_readings_visit_recorded_at', 'operational_readings', ['visit_id', 'recorded_at'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('remaining_t', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('progress_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_rate_tph', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_unload_finish', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_berth_release', sa.DateTime(timezone=True), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('data_quality', sa.Enum('VALID', 'STALE', 'INSUFFICIENT', 'INVALID', name='data_quality'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_rate_tph IS NULL OR effective_rate_tph > 0', name='ck_predictions_rate_positive'),
    sa.CheckConstraint('expected_berth_release IS NULL OR estimated_unload_finish IS NULL OR expected_berth_release >= estimated_unload_finish', name='ck_predictions_release_after_finish'),
    sa.CheckConstraint('progress_pct >= 0 AND progress_pct <= 100', name='ck_predictions_progress_range'),
    sa.CheckConstraint('remaining_t >= 0', name='ck_predictions_remaining_nonnegative'),
    sa.ForeignKeyConstraint(['visit_id'], ['vessel_visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictions_visit_generated_at', 'predictions', ['visit_id', 'generated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_predictions_visit_generated_at', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_operational_readings_visit_recorded_at', table_name='operational_readings')
    op.drop_table('operational_readings')
    op.drop_index('ix_delay_events_visit_id', table_name='delay_events')
    op.drop_index('ix_delay_events_category', table_name='delay_events')
    op.drop_table('delay_events')
    op.drop_index('ix_vessel_visits_vessel_id', table_name='vessel_visits')
    op.drop_index('ix_vessel_visits_status', table_name='vessel_visits')
    op.drop_index('ix_vessel_visits_planned_arrival', table_name='vessel_visits')
    op.drop_index('ix_vessel_visits_berth_id', table_name='vessel_visits')
    op.drop_table('vessel_visits')
    op.drop_index('ix_upcoming_calls_status', table_name='upcoming_vessel_calls')
    op.drop_index('ix_upcoming_calls_expected_arrival', table_name='upcoming_vessel_calls')
    op.drop_table('upcoming_vessel_calls')
    op.drop_table('vessels')
    op.drop_table('berths')
    op.drop_index('ix_audit_records_entity', table_name='audit_records')
    op.drop_index('ix_audit_records_created_at', table_name='audit_records')
    op.drop_table('audit_records')
        # Remove PostgreSQL enum types after dropping all dependent tables.
    op.execute("DROP TYPE IF EXISTS data_quality")
    op.execute("DROP TYPE IF EXISTS packaging_status")
    op.execute("DROP TYPE IF EXISTS unloading_status")
    op.execute("DROP TYPE IF EXISTS reading_source")
    op.execute("DROP TYPE IF EXISTS upcoming_call_status")
    op.execute("DROP TYPE IF EXISTS visit_status")
    op.execute("DROP TYPE IF EXISTS berth_status")
    op.execute("DROP TYPE IF EXISTS audit_action")
    # ### end Alembic commands ###
